---
- name: Installation install software-properties-common
  apt: name=software-properties-common

- name: Add repository PHP
  apt_repository:
    repo="ppa:ondrej/php"

- name: Update repositories
  apt: update_cache=yes

- name: Install PHP main packages
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'php{{ php_version }}-fpm', 'php{{ php_version }}-mysql' ]

- name: Install PHP modules/extensions
  apt: name={{ item }} update_cache=yes state=latest
  loop: "{{ php_packages }}"
