---
- hosts: 'all'
  become: true

  tasks:

    - import_role:
        name: provision.docker.daemon
      tags: ['daemon', 'install', 'docker' ]

    - import_role:
        name: provision.docker.pull_images
      tags: ['images', 'install', 'pull', 'docker' ]
